"""Translate authored desktop labels before formatting names or messages."""

SPANISH = {
    "Aki, your study companion.": "Aki, tu compañero de estudio.",
    "Your study companion.": "Tu compañero de estudio.",
    "Study companion": "Compañero de estudio",
    "Choose who cheers you on. This choice follows your account across devices.": "Elige quién te anima. Esta elección se sincroniza con tu cuenta en todos tus dispositivos.",
    "No companion": "Sin compañero",
    "ankiquest study companion…": "Compañero de estudio de ankiquest…",
    "Study companion saved across your devices.": "Compañero de estudio guardado en todos tus dispositivos.",
    "Cancel": "Cancelar", "Save": "Guardar", "Server": "Servidor", "Player": "Jugador", "Token": "Token",
    "Leaderboard": "Clasificación", "Friends": "Amigos", "Decks": "Mazos", "Notify": "Avisar",
    "Test connection": "Probar conexión", "Upload everything again": "Volver a subir todo",
    "Tell me when my place on the leaderboard changes": "Avísame cuando cambie mi puesto en la clasificación",
    "Warn me before my streak ends": "Avísame antes de que termine mi racha",
    "Deck completion notifications": "Avisos de mazos completados",
    "The people you pick hear once a day when you finish a shared deck.": "Se avisa una vez al día a las personas elegidas cuando completas un mazo compartido.",
    "Nobody else plays yet.": "Todavía no hay otros jugadores.", "All / none": "Todos / ninguno",
    "Nudge me when a place, my best day or the next level is within reach": "Dame un toque cuando pueda alcanzar un puesto, mi mejor día o el siguiente nivel",
    "Celebrate achievements, streak milestones and personal bests": "Celebrar logros, rachas y récords personales",
    "Update channel": "Canal de actualizaciones", "Stable releases": "Versiones estables",
    "Nightly builds (untested)": "Compilaciones nocturnas (sin probar)",
    "ankiquest: check for updates…": "ankiquest: buscar actualizaciones…",
    "This ankiquest is a local copy; it does not update itself.": "Este ankiquest es una copia local; no se actualiza solo.",
    "ankiquest: could not check for updates (%s)": "ankiquest: no se pudieron buscar actualizaciones (%s)",
    "ankiquest is up to date (%s).": "ankiquest está actualizado (%s).",
    "%s is available. Install it now? Anki needs a restart afterwards.": "%s está disponible. ¿Instalarlo ahora? Después hay que reiniciar Anki.",
    "ankiquest: could not download the update (%s)": "ankiquest: no se pudo descargar la actualización (%s)",
    "ankiquest: the update could not be installed (%s)": "ankiquest: no se pudo instalar la actualización (%s)",
    "ankiquest was updated. Restart Anki to use the new version.": "ankiquest se ha actualizado. Reinicia Anki para usar la nueva versión.",
    "#%d this week": "Puesto %d esta semana", "Lv %d  %s/%s XP": "Nv. %d  %s/%s XP",
    "🔥 %d day streak": "🔥 Racha de %d días", "streak at risk today": "racha en riesgo hoy", "📬 %d new": "📬 %d nuevos",
    "Set the server in ankiquest settings first.": "Configura primero el servidor en los ajustes de ankiquest.",
    "ankiquest settings saved.": "Ajustes de ankiquest guardados.",
    "Fill in the server, player and token first.": "Rellena primero el servidor, el jugador y el token.",
    "Connected as %s, level %d.": "Conectado como %s, nivel %d.",
    "Uploading your whole review history…": "Subiendo todo tu historial de repasos…",
    "Set the server, player and token in ankiquest settings first.": "Configura primero el servidor, el jugador y el token en los ajustes de ankiquest.",
    "ankiquest: could not load your decks (%s)": "ankiquest: no se pudieron cargar tus mazos (%s)",
    "Pick at least one person to notify, or share no decks.": "Elige al menos una persona a la que avisar o desactiva el envío de mazos.",
    "ankiquest: could not save your decks (%s)": "ankiquest: no se pudieron guardar tus mazos (%s)",
    "%d deck%s shared.": "Se comparten %d mazo%s.",
    "%d deck shared.": "Se comparte %d mazo.", "%d decks shared.": "Se comparten %d mazos.",
    "ankiquest settings…": "Ajustes de ankiquest…", "ankiquest deck notifications…": "Avisos de mazos de ankiquest…",
    "ankiquest inbox…": "Bandeja de entrada de ankiquest…", "ankiquest on the web…": "ankiquest en la web…",
    "ankiquest: could not sign in to the website (%s)": "ankiquest: no se pudo iniciar sesión en la web (%s)",
    "Display name (optional)": "Nombre visible (opcional)", "Username": "Nombre de usuario", "Password": "Contraseña",
    "Create a new account": "Crear una cuenta nueva", "Create account": "Crear cuenta", "Sign in": "Iniciar sesión",
    "Usernames use lowercase letters, numbers, - and _. Passwords need at least 10 characters.": "Los nombres de usuario usan minúsculas, números, - y _. Las contraseñas necesitan al menos 10 caracteres.",
    "Fill in the server, username and password.": "Rellena el servidor, el nombre de usuario y la contraseña.",
    "Connecting…": "Conectando…",
    "Sign in or create account…": "Iniciar sesión o crear cuenta…",
    "Sign in or create an account": "Inicia sesión o crea una cuenta",
    "ankiquest: sign in or create account…": "ankiquest: iniciar sesión o crear cuenta…",
    "Username or password not recognized.": "Nombre de usuario o contraseña no reconocidos.",
    "This server does not take new accounts. Ask whoever runs it for a token.": "Este servidor no admite cuentas nuevas. Pide un token a quien lo administra.",
    "That username is taken. Pick another one.": "Ese nombre de usuario ya existe. Elige otro.",
    "Too many attempts. Try again later.": "Demasiados intentos. Vuelve a intentarlo más tarde.",
    "The server could not sign you in (%s).": "El servidor no pudo iniciar tu sesión (%s).",
    "Could not reach the server (%s).": "No se pudo conectar con el servidor (%s).",
    "Signed in as %s.": "Sesión iniciada como %s.",
}


def tr(source, language=None):
    if language is None:
        from anki.lang import current_lang
        language = current_lang
    return SPANISH.get(source, source) if language.lower().replace("_", "-").split("-")[0] == "es" else source
